export { default as Header } from "./Header"
export { default as About } from "./About"
export { default as Services } from "./Services"
export { default as Work } from "./Work"
export { default as Clients } from "./Clients"
export { default as Contact } from "./Contact"
export { default as Footer } from "./Footer"