export { default as Navbar } from "./Navbar"
export { default as Heading } from "./Heading"
export { default as ServiceCard } from "./ServiceCard"
export { default as Swipe } from "./TestimonialCards"
export { default as OTPModal } from "./OTPModal"